version: '3'

services:

  generator:
    #build: ./generator
    image: generator
    environment:
      KAFKA_BROKER_URL: kafka1:9091
      TRANSACTIONS_TOPIC: queueing.transactions
      TRANSACTIONS_PER_SECOND: 10
    networks:
      kafka-network:    


  detector:
    #build: ./detector
    image: detector
    environment:
      KAFKA_BROKER_URL: kafka1:9091
      TRANSACTIONS_TOPIC: queueing.transactions
      LEGIT_TOPIC: streaming.transactions.legit
      FRAUD_TOPIC: streaming.transactions.fraud
    networks:
      kafka-network:

networks:
  kafka-network:
    driver: overlay
    external:
      name:  kafka-network
